my_templates/my_app/urls.py
from django.urls import path
from . import views

# register the app name space

app_name = 'my_app'

urlpatterns = [
    path('index', views.index_view, name='index'),
    path('simple/', views.simple_view, name='simple'),
] 

my_templates/my_templates/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),

]

handler404 = 'my_templates.views.my_custom_page_not_found_view'

my_templates/my_app/views.py
from django.shortcuts import render

# Create your views here.
def simple_view(request):
    data = {
        'number': 1,
        'letter': 'A',
        'name': 'Henrique',
        'some_list': [1, 2, 3, 4, 5, 6],
        'some_dictionary': [
            { 'name': 'Henrique', 'position': 'Software Engineer'},
            { 'name': 'Bruno', 'position': 'Line Manager'},
            { 'name': 'Rakesh', 'position': 'BCG Buddy'}
        ]
    }
    return render(request, 'my_app/example.html', context=data)

def index_view(request):
    return render(request, 'my_app/index.html')

my_templates/my_templates/views.py
from django.shortcuts import render

def my_custom_page_not_found_view(request, exception):
    return render(request, 'error_view.html', status=404)

my_templates/my_app/templates/my_app/example.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>THIS IS INSIDE THE BLOCK IN EXAMPLE.HTML</h1>
<img src="{% static 'my_app/bcgbackground.jpeg' %}" alt="">

{% endblock %}

{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Test template | <a href="{% url 'my_app:index' %}">Back to Index page</a> </h1>
    <p>My name is {{name}}</p>

    <p>A loop here</p>
    {% for number in some_list %}
        <p>{{number}}</p>
    {% endfor %}

    <p>A loop in a dictionary</p>
    {% for item in some_dictionary %}

    {% if item.position == 'Software Engineer' %}
    <div>
        <p>Employee: {{item.name}}/ Position: {{item.position}}</p>
    </div>
    {% else %}
    
    <h1>WILL KILLYOUUUU!!!</h1>

    {% endif %}
        
    {% endfor %}
</body>
</html> {% endcomment %}

my_templates/my_app/templates/my_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Index Page</h1>
    <h1>Go to <a href="{% url 'my_app:simple' %}">Simple page</a></h1>
</body>
</html>

my_templates/templates/base.html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1>THIS IS ABOVE THE BLOCK IN BASE.HTML</h1>
        {% block content %}
        {% endblock %}
        <h1>THIS IS BELOW THE BLOCK IN BASE.HTML</h1>
    </body>
    </html>

my_templates/templates/error_view.html
a    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>MY CUSTOM 404 PAGE</h1>
</body>
</html>