my_car_site/cars/urls.py
from django.urls import path
from . import views 

app_name = 'cars'

urlpatterns = [
    path('list', views.list, name='list'),
    path('add', views.add, name='add'),
    path('delete', views.delete, name='delete'),
]

my_car_site/my_car_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls'))
]

my_car_site/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    # pk
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
        return f"Car is {self.brand} {self.year}"

my_car_site/cars/views.py
from nis import cat
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    context = { 'all_cars': all_cars }

    return render(request, 'cars/list.html', context=context)

def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = request.POST['year']
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/add.html')

def delete(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse('cars:list'))
        except:
            print('pk not found!')
            return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/delete.html')

my_car_site/cars/templates/cars/add.html
{% extends "base.html" %}

{% block content %}
<h1>Add</h1>

<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <h2>Add a new car to the database</h2>
        <div class="form-group">
            <label for="brand">Brand:</label>
            <input class="form-control" type="text" id="brand" name="brand">
        </div>
        <div class="form-group">
            <label for="Year">Year</label>
            <input class="form-control" type="text" id="year" name="year">
        </div>
        <input class="btn btn-primary mt-1" type="submit">
    </form>
</div>
{% endblock %}

my_car_site/cars/templates/cars/delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete</h1>
<div class="container">
    <form action="" method="POST">
        {%csrf_token%}
        <div class="form-group">
            <label for="pk">PK Number:</label>
            <input class="form-control" type="text" id="pk" name="pk">
        </div>
        <input type="submit" class="btn btn-primary">
    </form>
</div>
{% endblock %}

my_car_site/cars/templates/cars/list.html
{% extends "base.html" %}

{% block content %}
<h1>List</h1>

<div class="container"> 
    <ul>
    {% for car in all_cars %}
        <li>{{car}}</li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

my_car_site/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cars:list' %}">List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cars:add' %}">Add</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cars:delete' %}">Remove</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content%}
    {% endblock %}

</body>

</html>